@startuml

actor President as "UN President"

rectangle database

rectangle "Reporting System" {
    usecase UC1 as "Capital Cities Reports"

    usecase UCa as "Display requested Capital
     City Report"

     President - UC1
     UC1 ..> UCa : include
     UC1 - database
@enduml